### ISSUE TITLE
Can't subst \$( in Textfile

### ISSUE THREAD

**Issue by datalogics-robb** [SConsProject/scons#4021]
**Describe the bug**
Generating .NET Core csproj files I needed to insert this string literal into the output
 `NETCore\bin\$(Platform)\$(Configuration)\`

But there does not seem to be any way to output the sequence `\$(`

To reproduce clone this:
   https://github.com/datalogics-robb/quote-test-scons

run `scons` to generate  GenFile.csproj and observe this string in the output:
`NETCore\bin\$Platform)\$Configuration)\`

SCons version 4.2.0
CPython 3.9.[67] tested  on Mac/Linux

**Comment by mwichmann** [comment]
Just capturing what was noted on Discord, although I got some details wrong there - the code uses some different conventions and it tripped me up. The `textfile` tool (which also implements `substfile`) sets up an action function which does substitution on the values in the `SUBST_DICT`, using `env.subst(value)`. With no keyword args, this defaults to `raw=0` which will end up calling `scons_subst` with `SUBST_CMD`.  But the intended usage here is just a plain textual substitution, not either the fancy "for command line" or the alternative "for signature", so this is probably not what's wanted in this context. Suggest adding `raw=1` (not `raw=True` as I said in the Discord thread).
