### ISSUE TITLE
dummyPopen object returned due to subprocess error causes unrelated exception in msvc/windows

### ISSUE THREAD

**Issue by jcbrill** [SConsProject/scons#4058]
**Current master branch on windows.** Lurking since python 3 string/bytes changes.

The dummyPopen object returned when an exception is caught in method _subproc of action.py causes cascading exceptions to be raised in the windows/msvc code path masking the original exception cause.

The issue can be reproduced by specifying an MSVC batch file that does not exist which will raise an exception: \
*[WinError 2] The system cannot find the file specified.*

Sample SConstruct:
```python
env = Environment(MSVC_USE_SCRIPT=r'C:\test_batch-file_does-not_exist.bat')
```

The causes of the cascading errors are:
* the dummyPopen object does not support the context management protocol (see issue 1 below)
* the dummyPopen object does not support returing an empty bytes string if the streams are not opened in text mode (see issue 2 below)

Given the above are resolved:
* the dummyPopen object returns an empty str/bytes for stderr (see issue 3 below)
* if the exception text is returned via stderr, there may be a missing newline (see issue 4 below)

The windows msvc code path (common.py) contains:

```python
    # Comments removed, debug calls removed, newlines added, and code annotated

    if args:
        popen = SCons.Action._subproc(env,
                                      '"%s" %s & set' % (vcbat, args),
                                      stdin='devnull',
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE)
    else:
        popen = SCons.Action._subproc(env,
                                      '"%s" & set' % vcbat,
                                      stdin='devnull',
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE)

    with popen.stdout:                  # <- Issue 1: dummyPopen does not support context management protocol
        stdout = popen.stdout.read()
        
    with popen.stderr:                  # <- Issue 1: dummyPopen does not support context management protocol
        stderr = popen.stderr.read()

    if sys.version_info.major == 3 and sys.version_info.minor < 6:
        from ctypes import windll
        OEM = "cp{}".format(windll.kernel32.GetConsoleOutputCP())
    else:
        OEM = "oem"
        
    if stderr:                               # <- Issue 3: stderr is empty str/bytes (no useful error message)
        sys.stderr.write(stderr.decode(OEM)) 
        sys.stderr.write('\n')               # <- [ADDED] Issue 4: stderr may not have trailing newline
                                             
    if popen.wait() != 0:
        raise IOError(stderr.decode(OEM))  # <- Issue 2: str returned instead of bytes
                                           # <- Issue 3: stderr is an empty str/bytes (no useful error message)
```

Description of cascading errors (line numbers may be off due to added line):

* Issue 1 (context management protocol):
    ```console
    AttributeError: __enter__:
        <lines removed>
        File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\common.py", line 276:
            with popen.stdout:
    ```
    Adding the context management protocol resolves issue 1.

* Issue 2 (str/bytes, text-mode/binary-mode):
    ```console
    AttributeError: 'str' object has no attribute 'decode':
        <lines removed>
        File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\common.py", line 300:
            raise IOError(stderr.decode(OEM))
    ```
    The windows/msvc code path expects the streams to return bytes.  However, the dummyPopen object returns empty strings.
    
    The fix for this particular problem is more involved, as some code paths explicitly open the streams in text mode.
    
    Fixing the str/bytes and text-mode/binary-mode problem resolves issue 2.
    
* Issue 3 (stderr is empty: no indication of underlying error):
    ```console
    OSError: :
        <lines removed>
        File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\common.py", line 300:
            raise IOError(stderr.decode(OEM))
    ```
    The exception is correctly raised.  However, the dummyPopen object returns an empty str/bytes for stderr which is not particulary useful.
    
    One potential fix for this problem is to return the exception text via stderr.  This becomes more problematic as clients of the stderr stream may use read() or readline().
    
    Fixing the stderr return text (via read and/or readline) resolves issue 3.
    
* Issue 4 (concatenated stderr output possible):
    ```console
    [WinError 2] The system cannot find the file specifiedOSError: [WinError 2] The system cannot find the file specified:
        <lines removed>
        File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\common.py", line 300:
            raise IOError(stderr.decode(OEM))
    ```
    
    Stderr is correctly populated with the exception text.  However, the stderr content is written to the console stderr prior to raising the exception.  Unfortunately, the exception text will not contain a trailing newline so the stderr.write() content and the exception content are effectively concatenated in the stderr stream.  At worst, an extra newline is written to stderr.
    
Expected output (given all changes):
```console
[WinError 2] The system cannot find the file specified
OSError: [WinError 2] The system cannot find the file specified:
    <lines removed>
    File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\common.py", line 301:
        raise IOError(stderr.decode(OEM))
 ```

**PR with potential fix(es) can be issued if desired:** https://github.com/jcbrill/scons/tree/jbrill-action-dummypopen

**Comment by mwichmann** [comment]
Thanks for the report. `_subproc` is unfortunate.  in trying to edge it towards something better without wholsale ripping it out (a lot of fear involved in messing with such a significant piece) I've probably left it broken in different ways than when I first started poking at it - already knew about the context-manager thing, but didn't have any reports of anyone tripping over that.  The reason for `_subproc` (which should be in Util.py, most likely) is "do something like `subprocess.Popen`, but account for the fact that information from the active SCons environment needs to be involved", and that seems to involve more than just passing `env=env` (with the value as the SCons env).

I'll try to look at your suggestions presently.   Absent having looked at them, I'd favor fixing it better than adding more bailing wire in the dummy popen - and rather have a method you call just like `subprocess.run`, which which does not depend on passing around a Popen object.  But maybe it's too disruptive to do that, maybe @bdbaddog will weigh in, as he'd have to approve.

**Comment by jcbrill** [comment]
I'm certain there are better ways to solve that particular problem that what I offered.

I stumbled on it some time ago but by hard-coding raising an exception to see how the exception handling works in common.py.  I didn't report it immediately for the same reason you mentioned.  

I am finishing work on a very minor enhancement (PR possible soon) in conjunction with user-defined scripts when I realized that the behavior could be induced by simply typing the wrong name for the script.  My guess is anyone that uses the wrong name eventually just figures it out.

**Comment by jcbrill** [comment]
Perhaps in this case, it easier to fix the symptom rather than the underlying problem: check if the user-defined script file exists after retrieving the value from the environment before calling script_env and possibly indicating an error directly in msvc_setup_env.  

Currently, an unchecked argument is passed all the way down to subprocess.Popen (msvc_setup_env, script_env, _subproc, subprocess.Popen).  Seems like it should be checked upon retrieval.  Just thinking out loud...

**Comment by bdbaddog** [comment]
> Perhaps in this case, it easier to fix the symptom rather than the underlying problem: check if the user-defined script file exists after retrieving the value from the environment before calling script_env and possibly indicating an error directly in msvc_setup_env.
> 
> Currently, an unchecked argument is passed all the way down to subprocess.Popen (msvc_setup_env, script_env, _subproc, subprocess.Popen). Seems like it should be checked upon retrieval. Just thinking out loud...

I like that. so check the first arg to verify it exists assuming it's some script/etc which is being run?
And then through a sane/recognizable exception for that?

**Comment by jcbrill** [comment]
>I like that. so check the first arg to verify it exists assuming it's some script/etc which is being run?
And then through a sane/recognizable exception for that?

Exactly.

Tested this morning:
```python
class FileNotFound(VisualCException):  # <- new
    pass                               # <- new
...

def msvc_setup_env(env):
    ...
    use_script = env.get('MSVC_USE_SCRIPT', True)
    if SCons.Util.is_String(use_script):
        use_script = use_script.strip()                                      # <- new
        if not os.path.exists(use_script):                                   # <- new
            raise FileNotFound('Script not found: "{}"'.format(use_script))  # <- new
        debug('use_script 1 %s' % repr(use_script))
        d = script_env(use_script)
    elif use_script:
    ...
```

```python
env = Environment(MSVC_USE_SCRIPT=r'C:\test_batch-file_does-not_exist.bat')

FileNotFound: Script not found: "C:\test_batch-file_does-not_exist.bat":
  <lines removed>
    File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\vc.py", line 946:
    raise FileNotFound('Script not found: "{}"'.format(use_script))
```

```python
env = Environment(MSVC_USE_SCRIPT=r'          ')

FileNotFound: Script not found: "":
  <lines removed>
  File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\vc.py", line 946:
    raise FileNotFound('Script not found: "{}"'.format(use_script))
```
Potential fix: https://github.com/jcbrill/scons/tree/jbrill-msvc-usescript

**Comment by jcbrill** [comment]
As for the original dummyPopen problem, one dead simple resolution for the msvc/windows code path (for errors other than file not found) **might be** simply passing ```error='raise'``` to _subproc.  

That is, let _subproc raise the actual exception and don't even bother with the dummyPopen object.

For example, in common.py:
```python
    if args:
        debug("Calling '%s %s'" % (vcbat, args))
        popen = SCons.Action._subproc(env,
                                      '"%s" %s & set' % (vcbat, args),
                                      stdin='devnull',
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE,
                                      error='raise')               # <- new
    else:
        debug("Calling '%s'" % vcbat)
        popen = SCons.Action._subproc(env,
                                      '"%s" & set' % vcbat,
                                      stdin='devnull',
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE
                                      error='raise')                # <- new
```

Have not had time to test yet...

**Comment by bdbaddog** [comment]
Instead of `FileNotFound` how about `MSVCScriptNotFound` for a more informative exception?
And maybe something like "script specified by MSVC_USE_SCRIPT not found". 
So it's super clear what failed, and maybe how to fix

**Comment by jcbrill** [comment]
Sure. 

Previous examples re-run:

```python
env = Environment(MSVC_USE_SCRIPT=r'C:\test_batch-file_does-not_exist.bat')

MSVCScriptNotFound: Script specified by MSVC_USE_SCRIPT not found: "C:\test_batch-file_does-not_exist.bat":
  <lines removed>
  File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\vc.py", line 946:
    raise MSVCScriptNotFound('Script specified by MSVC_USE_SCRIPT not found: "{}"'.format(use_script))

env = Environment(MSVC_USE_SCRIPT=r'   ')

MSVCScriptNotFound: Script specified by MSVC_USE_SCRIPT not found: "":
  <lines removed>
  File "S:\SCons\scons\scripts\..\SCons\Tool\MSCommon\vc.py", line 946:
    raise MSVCScriptNotFound('Script specified by MSVC_USE_SCRIPT not found: "{}"'.format(use_script))
```

Code updated: https://github.com/jcbrill/scons/tree/jbrill-msvc-usescript

**Comment by jcbrill** [comment]
Manually commenting-out the MSVCScriptNotFound exception to test using  ```error='raise``` in _subproc (https://github.com/SCons/scons/issues/4058#issuecomment-968283688 above) results in the following exceptions:
```python
env = Environment(MSVC_USE_SCRIPT=r'C:\test_batch-file_does-not_exist.bat')

FileNotFoundError: [WinError 2] The system cannot find the file specified:
  File "S:\SCons\Test-Arg\SConstruct", line 28:
    env = Environment(MSVC_USE_SCRIPT=r'C:\test_batch-file_does-not_exist.bat')
  <lines removed>

env = Environment(MSVC_USE_SCRIPT=r'   ')

OSError: [WinError 87] The parameter is incorrect:
  File "S:\SCons\Test-Arg\SConstruct", line 30:
    env = Environment(MSVC_USE_SCRIPT=r'   ')
  <lines removed>
```

It may be a good idea to add the ```error='raise'``` argument to the two _subproc invocations in common.py to avoid the dummyPopen problems when subprocess fails for any reason given a valid script file.

Trivial to add and update.

**Comment by mwichmann** [comment]
> Instead of `FileNotFound` how about `MSVCScriptNotFound` for a more informative exception? And maybe something like "script specified by MSVC_USE_SCRIPT not found". So it's super clear what failed, and maybe how to fix

Indeed, the advantage of an SCons-defined exception is it trims (or at least tries) the traceback down and doesn't show the trail down into the Python stdlib after something is already wrong.

**Comment by jcbrill** [comment]
In addition to the MSVCScriptNotFound additions above, I propose minor tweaking of the code in common.py to bypass the dummyPopen problems when subprocess raises an exception:
```python
def get_output(vcbat, args=None, env=None):
    ...

    if args:
        call_str = '"{}" {}'.format(vcbat, args)
    else:
        call_str = '"{}"'.format(vcbat)

    try:
        debug("Calling '%s'" % call_str)
        popen = SCons.Action._subproc(env,
                                      '%s & set' % call_str,
                                      stdin='devnull',
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE,
                                      error='raise')
    except Exception as e:
        raise IOError(str(e))
  
    with popen.stdout:
        stdout = popen.stdout.read()
    with popen.stderr:
        stderr = popen.stderr.read()

    if sys.version_info.major == 3 and sys.version_info.minor < 6:
        from ctypes import windll
        OEM = "cp{}".format(windll.kernel32.GetConsoleOutputCP())
    else:
        OEM = "oem"  
    if stderr:
        sys.stderr.write(stderr.decode(OEM))
    if popen.wait() != 0:
        raise IOError(stderr.decode(OEM))
 
    ...
```
Allow _subproc to raise the exception bypassing the dummyPopen problems and raise an exception similar to the code a little further along (```raise IOError(str(e))``` instead of ```raise IOError(stderr.decode(OEM))```).

Debug output fragments to verify call strings for both paths:
```console
# based on Environment(MSVC_VERSION='14.3', MSVC_UWP_APP='1')
...
Calling '"C:\Software\MSVS143\VC\Auxiliary\Build\vcvars64.bat" store'
...
Calling '"C:\Software\MSVS143\VC\Auxiliary\Build\vcvars64.bat"'
...
```

Force _subproc exceptions by manually commenting out raising MSVCScriptNotFound:
```console
OSError: [WinError 87] The parameter is incorrect:
  File "S:\SCons\Test-Arg\SConstruct", line 30:
    env = Environment(MSVC_USE_SCRIPT=r'   ')
  <lines removed>

OSError: [WinError 87] The parameter is incorrect:
  File "S:\SCons\Test-Arg\SConstruct", line 30:
    env = Environment(MSVC_USE_SCRIPT=r'   ')
  <lines removed>
```
The full stack trace (not shown) is definitely easier to read than when raised from subprocess.

Best of both worlds? 

User script error: detected early and MSVCScriptNotFound exception raised.
Subprocess error: exception caught and raised to produce more legible stack trace and avoiding dummyPopen processing.

**Comment by jcbrill** [comment]
Proposed changes: https://github.com/jcbrill/scons/tree/jbrill-msvc-usescript
PR is desired.

Comments:
* bypass dummyPopen issues by passing ```error='raise'``` and raising appropriate exception in get_output.
* verify user specified script exists and raise exception if it doesn't in msvc_setup_env.
* the debug string now has double quotes around the batch file name where the previous version was unquoted.

Changes to MSCommon/common.py
```python
    if args:
        call_str = '"{}" {}'.format(vcbat, args)
    else:
        call_str = '"{}"'.format(vcbat)

    debug("Calling '%s'" % call_str)

    call_str += ' & set'

    # subprocess documentation notes:
    #    The most common exception raised is OSError.
    #    A ValueError will be raised if Popen is called with invalid arguments.
    #    Exceptions defined subprocess module all inherit from SubprocessError.
    try:
        popen = SCons.Action._subproc(env,
                                      call_str,
                                      stdin='devnull',
                                      stdout=subprocess.PIPE,
                                      stderr=subprocess.PIPE,
                                      error='raise')
    except OSError as e:
        raise OSError(str(e))
    except ValueError as e:
        raise ValueError(str(e))
    except SubprocessError as e:
        raise SubprocessError(str(e))
    except Exception as e:
        raise Exception(str(e))
```

Changes to MSCommon/vc.py
```python
    if SCons.Util.is_String(use_script):
        use_script = use_script.strip()
        if not os.path.exists(use_script):
            raise MSVCScriptNotFound('Script specified by MSVC_USE_SCRIPT not found: "{}"'.format(use_script))
        debug('use_script 1 %s' % repr(use_script))
        d = script_env(use_script)
```

**Comment by bdbaddog** [comment]
Please PR it. It'll be easier to compare that way for me.

**Comment by mwichmann** [comment]
On Issue 2 up at the top: there were some go-rounds on WIndows and whether text mode in subprocess was usable.  I think the eventual (unfortunate) conclusion by someone - and maybe it was @jcbrill - was that it wasn't always - there were problems with non-English Visual Studio installs if memory serves.  Pretty sure the dummyPopen never reacted to those changes, so that part looks like a good catch.

**Comment by mwichmann** [comment]
In addition, I think the SCons tools are a little careless about using try blocks to wrap subprocess calls - it's not at all impossible for something to fail when calling out to an external command, so I'm +1 on this being added to the msvc tool.

**Comment by jcbrill** [comment]
@bdbaddog I apologize for being dense, PR: (a) the dummyPopen implementation, (b) the changes for using a script (common.py, vc.py) plus bypassing dummyPopen, or (c) both?

If both, does it make sense for me to merge the two together and PR the result?

**Comment by jcbrill** [comment]
PR #4063 does not have any changes to the dummyPopen object in _subproc.

@mwichmann Should the dummyPopen object be left well enough alone for now?

dummyPopen implementation: https://github.com/jcbrill/scons/tree/jbrill-action-dummypopen

Writing an additional newline to stderr was removed in anticipation that the code to bypass the dummyPopen object will be accepted.  Therefore, all changes in the branch referenced above are now solely modifications to the dummyPopen object.

**Comment by jcbrill** [comment]
> On Issue 2 up at the top: there were some go-rounds on WIndows and whether text mode in subprocess was usable. I think the eventual (unfortunate) conclusion by someone - and maybe it was @jcbrill - was that it wasn't always - there were problems with non-English Visual Studio installs if memory serves

Can't take credit for that one.

**Comment by mwichmann** [comment]
Okay, some prospecting... some of the sordid story is in #3572

**Comment by mwichmann** [comment]
looks like we can simplify a bit now 3.5 is no longer supported.

**Comment by jcbrill** [comment]
> Okay, some prospecting... some of the sordid story is in #3572

@mwichmann Your recall is impressive.  

I wasn't involved with the encoding issues in that particular issue.  Early on in support VS2019, I did run into the powershell and telemetry issue which I believe was tangential to whatever issue was being discussed at the time.  I can't seem to find the posts.  There was a debate at the time if powershell should be added to the path or not and adding the MS environment variable to skip sending telemetry information.

**Comment by jcbrill** [comment]
One possibility is the approach taken with setuptools (https://github.com/pypa/setuptools/blob/main/setuptools/msvc.py). 

Launch a new instance of cmd.exe requesting Unicode output (/u) and decoding unicode:

```python
    try:
        out = subprocess.check_output(
            'cmd /u /c "{}" {} && set'.format(vcvarsall, plat_spec),
            stderr=subprocess.STDOUT,
        ).decode('utf-16le', errors='replace')
    except subprocess.CalledProcessError as exc:
        raise distutils.errors.DistutilsPlatformError(
            "Error executing {}".format(exc.cmd)
        ) from exc
```

I took this approach in my vsdetect.py script along with enabling command extensions and delayed expansion.  

However, I did run into some issues decoding stderr as not all tools seem to be unicode enabled/compliant/?.  The msvc batch files occasionally write an error string to stderr that is not fatal (e.g., querying a registry key that may not exist) and then proceeding accordingly.

**Comment by mwichmann** [comment]
Just adding the note that `dummyPopen` now operates as a context manager, after PR #4088.  I still want to rework this stuff, though.

**Comment by jcbrill** [comment]
Perhaps the issue report above is misleading.

From above:
```py
    with popen.stdout:                  # <- Issue 1: dummyPopen does not support context management protocol
        stdout = popen.stdout.read()
        
    with popen.stderr:                  # <- Issue 1: dummyPopen does not support context management protocol
        stderr = popen.stderr.read()
```

While the comment indicates that dummyPopen does not support the context management protocol, it is actually the **_nested dummy file class f_** instances for stdout and stderr that do not support the context management protocol.

Shouldn't the context management protocol be added to the nested file object or am I just being denser than usual?
```py
        class dummyPopen:
            ...
            def __enter__(self): 
                return self
            def __exit__(self, *args): 
                pass
            ...
            stdin = None
            class f:
                def read(self): return ''
                def readline(self): return ''
                def __iter__(self): return iter(())
                def __enter__(self):                    # <- file object context management protocol
                    return self
                def __exit__(self, *args):              # <- file object context management protocol
                    pass
            stdout = stderr = f()
        pobj = dummyPopen(e)
```

**Comment by mwichmann** [comment]
Yes, quite right, if we're going to still use `with` on stdout/stderr, then that should be turned into a context manager too.

**Comment by jcbrill** [comment]
@mwichmann Can this be closed?

The new `scons_subproc_run` (#4300) doesn't use the `dummyPopen` instance.  `_subproc` is deprecated.

Still possible with code using `_subproc`, but I'm not sure this issue was ever reported in the wild.

**Comment by mwichmann** [comment]
Agree, the new routine was intended to avoid getting into those situations, rather than faking something on failure we switch to a mode where there are expected results on failure that code actually looks for. Closing.
