### ISSUE TITLE
Scons 4.2.0 and Python 3.10: test SCons/ActionTests.py failed

### ISSUE THREAD

**Issue by band-a-prend** [SConsProject/scons#4074]
Please, see the discussion of this problem in [scons-users mailing list](https://pairlist4.pair.net/pipermail/scons-users/2021-December/008697.html).

------
While running Scons tests with python 3.10.1 the `SCons/ActionTests.py` failed for Python 3.10 with error:
```
FAIL: test_function_contents (__main__.ObjectContentsTestCase)
Test that Action._function_contents works
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/var/tmp/portage/dev-util/scons-4.2.0-r2/work/scons-4.2.0/SCons/ActionTests.py", line 2258, in test_function_contents
    assert c == expected[sys.version_info[:2]], "Got\n" + repr(c) + "\nExpected \n" + "\n" + repr(
AssertionError: Got
bytearray(b'3, 3, 0, 0,(),(),(|\x00S\x00),(),()')
Expected 
 
bytearray(b'3, 3, 0, 0,(N.),(),(|\x00S\x00),(),()')
```
 
Is it realy expected value for Python3.10 as mentioned in https://github.com/SCons/scons/blob/9e1168ab8f500ee8602a1098050d38c3ee1e3260/SCons/ActionTests.py#L2254 ?
 
For Python 3.9 the expected value is `bytearray(b'3, 3, 0, 0,(),(),(|\x00S\x00),(),()')`.
Should for Python 3.10.1 expected the same value instead of current expected value?

The problem doesn't present when build scons and run tests with Python 3.10.0.
 
* Version of SCons : 4.2.0
* Version of Python : 3.10.1 
* How you installed SCons : Gentoo package
* What Platform are you on? (Linux/Windows and which version) : Gentoo Linux

**Comment by bdbaddog** [comment]
Fixed in commit f21b2dd4af2874401eac65f24ef5142216e0a284
