### ISSUE TITLE
Value/Alias Nodes default to up-to-date

### ISSUE THREAD

**Issue by ghost** [SConsProject/scons#4079]
Just looking to confirm the behavior here (I think I tracked down the bug/error), just want to make sure this is actually a bug (and not expected behavior).

SCons 4.1.0

TLDR; File: `SCons/Node/__init__.py`, Method: `children_are_up_to_date` -- Return when no Node children exist (state==0)=True, this correct ?

Test:
Create an Alias/Value node and drop them as a dependency of something else that will be built (or force them to be part of the build in any other chosen way). In my use-case I'm abusing an Alias (for it's unique namespace ability), using a Value() as it's target and running an Action() when this target changes.
Now what I believe is a bug. The action of my Alias above will not be executed (so long as only Alias/Value nodes are the only children of this node). This seems to occur because the Alias/Value node will be considered to be up-to-date (as per code, so long as it's children are considered up-to-date, which when no children exist, by the class method is True). Intuitively, I think this should be the opposite (always, if not at least by default). i.e. Alias/Value nodes default to being NOT up-to-date.

As a workaround to make the above scenario work, I'm currently using AlwaysBuild() on these node types to get them to be considered not up-to-date (as this condition is early-exit checked in the that method, forcing the node to not be up-to-date).

**Comment by bdbaddog** [comment]
Can you create a simple reproducer for us to look at?

**Comment by bdbaddog** [comment]
Also try the latest version of SCons 4.3.0.
Which version of Python?
Which OS?
All the questions which are in the issue template which you seem to have ignored/deleted...

**Comment by bdbaddog** [comment]
## Please bring your issue to the SCons users mailing list before filing an issue here
## See: https://scons.org/bugs.html
## or join our Discord server : https://discord.gg/bXVpWAy


**Describe the bug**
A clear and concise description of what the bug is.

**Required information**
* Link to SCons Users thread discussing your issue.
* Version of SCons
* Version of Python
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc)
* How you installed SCons
* What Platform are you on? (Linux/Windows and which version)
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.
* How you invoke scons (The command line you're using "scons --flags some_arguments")

**Comment by ghost** [comment]
I didn't get an issue template when creating this issue. However, seeing it now I'll fill in the questions and resubmit via the mailing list.

**Comment by bdbaddog** [comment]
That's odd.  Did you click create issue and the bug buttons on github?

If you can join the discord server, that tends to be a bit more interactive to work on such..

**Comment by ghost** [comment]
Ah I see. Yes I created an issue in that manner. However, I didn't select Bug/Feature but went with a blank issue (as I wasn't sure if this was defined behavior or actually a bug). In any case I've bounced this issue onto the users mailing list.

**Comment by bdbaddog** [comment]
> Ah I see. Yes I created an issue in that manner. However, I didn't select Bug/Feature but went with a blank issue (as I wasn't sure if this was defined behavior or actually a bug). In any case I've bounced this issue onto the users mailing list.

Interesting.. Didn't realize you could do such! Learn something new every day.. ;)
We'll have to disable the blank issues to avoid this going forward.

**Comment by ghost** [comment]
@bdbaddog Confirmed behavior of Alias/Value Node's is correct. When both Node's are created they are in an up-to-date state (and with thus not be built, unless explicitly requested, via AlwaysBuild()).
