### ISSUE TITLE
typo bug

### ISSUE THREAD

**Issue by Vishwajith-K** [SConsProject/scons#4096]
~constrcution~
construction

https://github.com/SCons/scons/blob/71052a843d30210c77de621afe482baa0dd491da/doc/user/troubleshoot.xml#L339

**Comment by mwichmann** [comment]
Good catch.  Been gradually transitioning mentions to an entiry (`&consvars;` for the plural, `&consvar;` for the signular) which reduces the chances of finger-fumbles of this kind.

**Comment by Vishwajith-K** [comment]
Is it added?
Can you share me file name where the variables are defined?
Do you want me to add the variable?
If it's already added, do you want me to update the doc file with corresponding var?

**Comment by mwichmann** [comment]
The xml entites are partly in `doc/scons.mod` and partly in files generated from documentation sources, checked in in `doc/generated/*.mod`

**Comment by mwichmann** [comment]
I'll link a PR for this shortly.
