### ISSUE TITLE
AppendUnique  breaks CPPScanner when using defs without value

### ISSUE THREAD

**Issue by Inviz** [SConsProject/scons#4108]
`AppendUnique` turns string values into tuples with single values, breaking `dictify_CPPDEFINES`, and thus CPPScanner.

Details of my investigation here: https://community.platformio.org/t/libraries-included-inside-conditional-guard-are-still-added-to-the-dep-graph-by-ldf/26326/4

1) Platformio inside its ProcessFlags parses defs like `-DA -DB=C into ('A', ('B', 'C'))` for `env[“CPPDEFINES”]`
2) `libopencm3.py` script tries to add `-DSTM32F4` def via `env.ApppendUnique(CPPDEFINES=["STM32F4"])` (which is not really necessary, but that’s irrelevant)
3) **`env.AppendUnique` turns all previous defs without value (that were strings) into tuples with single value, and adds new values also as tuples**: `(('A', ), ('B', 'C'), ('STM32F4',))`
4) **CPPScanner expects defs without value to be strings, but any invocation of `env.AppendUnique` breaks that expectation**
5) Scons crashes:
```python
def dictify_CPPDEFINES(env):
    cppdefines = env.get('CPPDEFINES', {})
    if cppdefines is None:
        return {}
    if SCons.Util.is_Sequence(cppdefines):
        result = {}
        for c in cppdefines:
            if SCons.Util.is_Sequence(c):
                result[c[0]] = c[1] # <-- [1] tuple index out of range
            else:
                result[c] = None
        return result
```

**Required information**
* Version of SCons 4.3
* Version of Python 3.9
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc) brew
* How you installed SCons viaPIO
* What Platform are you on? (Linux/Windows and which version) mac

**Comment by mwichmann** [comment]
Looks like it's easy enough to patch the hole here, without necessarily tackling the deeper question of why we have keep converting the type of CPPDEFINES. 

Do you have a simple example that actually tickles the `IndexError`

Meanwhile, /me scratches head over:
```python
env = Environment()
env.Append(CPPDEFINES="A")
env.Append(CPPDEFINES="B=C")
env.Append(CPPDEFINES=["STM32F4"])
env.AppendUnique(CPPDEFINES=["STM32F4"])
```
Showing
```
env['CPPDEFINES']=['A']
env['CPPDEFINES']=['A', 'B=C']
env['CPPDEFINES']=['A', 'B=C', 'STM32F4']
env['CPPDEFINES']=[('A',), ('B=C',), ('STM32F4',)]
```
as in - why does Append's speciai-case handling for CPPDEFINES not tuple-ify and AppendUnique's does?

**Comment by Inviz** [comment]
I think `dictify_CPPDEFINES(env)` is enough to invoke the issue:
```
env = Environment()
env.AppendUnique(CPPDEFINES="A")
dictify_CPPDEFINES(env)
```
 

I think more proper example  of difference would  be to `env.Append(CPPDEFINES=("B", "C"))` (or whatever syntax is to append the tuple, I'm not fluent in python). You'll see that it'll add tuble for `("B", "C")`. But for case with no value (e.g. `"B"`) it will keep the string in it. So that means `AppendUnique` doesn't simplify the values, while `Append` does (and then other things rely on it)

**Comment by mwichmann** [comment]
Indeed, it is... 
```python
from SCons.Scanner.C import dictify_CPPDEFINES
d = dictify_CPPDEFINES(env)
```
