### ISSUE TITLE
scons: Reading SConscript - name 'Options' is not defined

### ISSUE THREAD

**Issue by 0pLuS0** [SConsProject/scons#4112]
**Required information**
* Version of SCons - ```4.2.0```
* Version of Python - ```python2-2.7.18 & python3-3.9.10```
* How you installed SCons - ```Linux distribution supplied package```
* What Platform are you on? ```Slackware 15.0 x86_64```
* How to reproduce your issue?  - ```compiling tolua++-1.0.93 against scons 4.2.0```

**Describe the bug**

tolua++-1.0.93 will not compile with scons 4.2.0 installed.

```Terminal output error message;```

scons: Reading SConscript files ...
NameError: name 'Options' is not defined:
  File "/tmp/foo/tolua++-1.0.93/SConstruct", line 19:
    opts = Options(["config_"+options_file+".py", "custom.py", "custom_"+options_file+".py"], ARGUMENTS)

I know help resources were mentioned, but given the nature of this, compiling tolua++-1.0.93 against scons 4.2.0 I assumed is a known issue someone could help me solve this here?

THANKS

Here's the SConstruct from tolua++-1.0.93

[SConstruct.txt](https://github.com/SCons/scons/files/8222205/SConstruct.txt)

**Comment by mwichmann** [comment]
`Options` hasn't been a thing in SCons since before 1.0 (14+ years ago). Try renaaming the call to `Variables`.

**Comment by bdbaddog** [comment]
Your should probably go check with that project to see if they have updated SCons logic to work with newer SCons.

**Comment by bdbaddog** [comment]
Also please include a URL to the git repo for the project you're trying to compile.

**Comment by 0pLuS0** [comment]
Check what project? I'm only trying to compile tolua++-1.0.93.

tolua++-1.0.93 hasn't changed in years, looks like it's dead.

https://github.com/LuaDist/toluapp

I had hoped that Arch Linux would have had a patch for tolua++ or scons, they're usually a good place to check, but there's nothing, and Arch lists compiling Scons 4.3 but nothing listed as a patch there, so I wonder how they are pulling it off...

https://archlinux.org/packages/extra/any/scons/
https://archlinux.org/packages/community/x86_64/tolua++/

As a Slacker I always check with Arch when there are no patches from Slack, to see if Arch has them...

You mean changing;

```opts = Options(["config_"+options_file+".py", "custom.py", "custom_"+options_file+".py"], ARGUMENTS)```

Like this?

opts = ```Variables```(["config_"+options_file+".py", "custom.py", "custom_"+options_file+".py"], ARGUMENTS)

P.S. I changed the line to the Variables shown above and now I got this output from the terminal;

scons: Reading SConscript files ...
********* tolua is  bin/tolua++_bootstrap
AttributeError: '_io.TextIOWrapper' object has no attribute 'xreadlines':
  File "/tmp/foo/tolua++-1.0.93/SConstruct", line 160:
    SConscript('src/bin/SCsub')
  File "/usr/lib64/python3.9/site-packages/SCons/Script/SConscript.py", line 660:
    return method(*args, **kw)
  File "/usr/lib64/python3.9/site-packages/SCons/Script/SConscript.py", line 597:
    return _SConscript(self.fs, *files, **subst_kw)
  File "/usr/lib64/python3.9/site-packages/SCons/Script/SConscript.py", line 285:
    exec(compile(scriptdata, scriptname, 'exec'), call_stack[-1].globals)
  File "/tmp/foo/tolua++-1.0.93/src/bin/SCsub", line 8:
    toluabind = env.LuaBinding('toluabind.c', 'tolua_scons.pkg', 'tolua', bootstrap = True)
  File "/tmp/foo/tolua++-1.0.93/SConstruct", line 115:
    self.pkg_scan_dep(target, psource)
  File "/tmp/foo/tolua++-1.0.93/SConstruct", line 68:
    for linea in pkg.xreadlines():

**Comment by bdbaddog** [comment]
I"m going to close this bug as it is not an issue with SCons.
If you'd like help please feel free to join the users mailing list or our discord server.
https://discord.gg/pejaFYrD9n

**Comment by 0pLuS0** [comment]
@bdbaddog 

Well, I guess it depends on how you want to look at it, since tolua++ seems pretty dead as a project, I was hoping someone could please take the time and try compile tolua++ with the latest scons installed.

It is afterall an issue I'm having trying to use the latest scons.

I'm kindly asking for a favor, if someone can please take the time to do this, it would be greatly appreciated, I don't want to end up running an older version of scons, which at present, I can only use 2.5.1 with tolua++.

THANKS

**Comment by 0pLuS0** [comment]
Ahhh after making all this, I am really sorry, I later found out I no longer need tolua++

SORRY for this post, thanks for the replies.

**Comment by mwichmann** [comment]
Well, glad you're not blocked anyway!  There was a simple suggestion earlier: replace Options with Variables, as that was a compatible change from long ago.  If you no longer need the project, then no worries.

**Comment by 0pLuS0** [comment]
I tried Variables, I showed that before...

But it's all good now, sorry again for the post.

Take care...
