### ISSUE TITLE
doc: behavior of Fortran subsystem needs more explanation

### ISSUE THREAD

**Issue by mwichmann** [SConsProject/scons#4173]
There doesn't seem to be any formal description of the set of Fortran tools - particularly vectoring to "different" compilers based on the source filename suffix.

There are 15 Fortran tool modules:  `aixf77.py`, `cvf.py`, `f03.py`, `f08.py`, `f77.py`, `f90.py`, `f95.py`, `fortran.py`, `g77.py`, `gfortran.py`, `ifl.py`, `ifort.py`, `sunf77.py`, `sunf90.py`, `sunf95.py`. 12 of these import from `FortranCommon` and call `add_all_to_env` which adds all the known "dialects" to the construction environment: `FORTRAN`, `F77`, `F90`, `F95`, `F03`, `F08` (there is a new Fortran standard, 2018, which SCons doesn't have anything for).  One of the missing three modules is a kind of wrapper - `gfortran.py` so it's really all-but-two (`aixf77` and `cvf`). Of course, only one tool ever runs for a given environment setup, since SCons "stops there" once it's either found the first one from its autodetect list, or finds the one in the tool list.

With this setup, the command name is autodetected (based on platform rules), and ends up set as the compiler `$FORTRAN` and all of the standards variants; SCons dispatches to the named one if the suffix is not one of the base ones.  That is, `FORTRAN` and associated cvars are used if a `.f`, while `F77` is used if a `.f77`.  This allows the developer to override defaults if some kind of special handling is needed for a specific variant.

You can probably deduce much of this if reading all of the entries (the many tool names, the many construction var names) but I certainly don't find it clear, it has taken a fair bit of digging in the code in my case.  If would be nicer if there was a single section that described the behavior from the SConscript witer's perspective, leaving the individual var-and-tool entries to fill in specific details when you need them.

gfortran itself makes some assumptions that aren't really reflected here:  files named `.f` are the old fixed-form style even if they're written to a very new Fortran standard, while files named `.f90` are free-form (even in the very latest Fortran standard, the old fixed-form style remains a supported thing).  The Intel Fortran appears to follow this convention as well.  This kind of unfortunate choice makes it seem like Fortran 90 is some kind of magical thing, where it's just a dividing line between the two syntax styles.  Meanwhile, the `gfortran` tool has a special feature: after everything is set up, it rewrites itself as the compiler for all of the variants:
```py
    fortran.generate(env)

    for dialect in ['F77', 'F90', 'FORTRAN', 'F95', 'F03', 'F08']:
        env['%s' % dialect] = 'gfortran'
        env['SH%s' % dialect] = '$%s' % dialect
```
`ifort` does this as well, using its own name of course, although for a smaller number of dialects:
```py
    fc = 'ifort'

    for dialect in ['F77', 'F90', 'FORTRAN', 'F95']:
        env['%s' % dialect] = fc
        env['SH%s' % dialect] = '$%s' % dialect
```

**Comment by mwichmann** [comment]
Here's a proposal (the paste from formatted html loses linking to other manpage sections) - would this make sense? (This would replace the current, shorter section on Fortran file suffixes that appears near the very end of the manpage):

----------

There are several ways source file suffixes impact the behavior of SCons when working with Fortran language code (not all are system-specific, but they are included here for completeness).

As the Fortran language has evolved through multiple standards editions, there is sometimes a need to handle files from different language generations differently. To this end, SCons dispatches to a different compiler dialect setup (expressed as a set of construction variables) depending on the file suffix. By default, all of these setups start out the same, but individual construction variables can be modified as needed to tune a given dialect. Each of these dialacts has a tool specification module whose documentation describes the construction variables associated with that dialect: .f (as well as .for and .ftn) in `fortran`; .f77 in `f77`; .f90 in `f90`; .f95 in `f95`; .f03 in `f03`; .f08 in `f08`.

While SCons recognizes multiple dialects, the convention of various available Fortran compilers is to assign an actual meaning to only two of these: .f (as well as .for and .ftn) refers to the fixed-format source code that was the only available option in FORTRAN 77 and earlier, and .f90 refers to free-format source code which became available starting with the Fortran 90 standard. Some compilers recognize the other later "variants" (e.g. .f03) as equivalent to .f90 for this purpose, while some do not - check the documentation for your compiler. A number of experts suggest sticking to just .f and .f90 as Fortran filename suffixes. Note that this is a convention applied by the compiler, not behavior imposed by SCons. The fixed/free form determination can usually be set explicitly with compiler flags, overriding the assumption that may be made based on the source file suffix.

The source file suffix does not imply conformance with the similarly-named Fortran standard - a suffix of .f08 does not mean you are compiling specifically for Fortran 2008. Normally, compilers provide command-line options for making this selection (e.g. `-std=f2008` for gfortran).

On a case-sensitive system such as Linux or UNIX, a file with a an upper-cased suffix from the set `.F`, `.FOR`, `.FTN`, `.F90`, `.F95`, `.F03` and `.F08`. is treated as a Fortran source file which shall first be run through the standard C preprocessor. The lower-cased versions of these suffixes do not trigger this behavior. On systems which do not distinguish between uppper and lower case in filenames, this behavior is not available, but files suffixed with either `.FPP` or `.fpp` are always passed to the preprocessor first. This matches the convention of gfortran from the GNU Compiler Collection, and is also be followed by certain other Fortran compilers.

*Run through the C preprocessor* here means that a different set of construction variables will be applied in constructed commands, for example `$FORTRANPPCOM and `$FORTRANPPCOMSTR` instead of `$FORTRANCOM` and `$FORTRANCOMSTR`. See the Fortran-related construction variables for more details.

**Comment by bdbaddog** [comment]
Your suggested text looks good to me
