### ISSUE TITLE
'cl' is not recognized as an internal or external command

### ISSUE THREAD

**Issue by 18611429192** [SConsProject/scons#4188]
My system is Windows7, Python is 3.7.4 and scons is 4.3.0.

I have add the `C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.28.29333\bin\Hostx64\x64` to my PATH. And then I can use the cl command in cmd. 

But when I use scosn command to build a project,  an error has occurred.

`'cl' is not recognized as an internal or external command`

What should I do?

**Comment by bdbaddog** [comment]
Please bring your issue to the [users mailing list](https://pairlist4.pair.net/mailman/listinfo/scons-users) or our [discord server](https://discord.gg/bXVpWAy).
(Did you notice the text in the issue when you clicked new issue?)

If you are using the cmd shell:
`set SCONS_MSCOMMON_DEBUG=ms_trace.log`
If you are using powershell:
`$env:SCONS_MSCOMMON_DEBUG=ms_trace.log`

Then run scons, and attach that file to this issue.
(or better bring it to our users mailing list or scons discord server)

**Comment by mwichmann** [comment]
Just for information, SCons won't, by default, use your environment variables like PATH.  For Visual Studio / Build Tools from 2017 on, it uses the `vswhere.exe` command to work out where the compiler lives.  The debug dump should show (along with many other things) the process of trying to do this, and *hopefully* give clues as to why it's not finding it.

**Comment by 18611429192** [comment]
I didn't notice this list before.
Thank you for the advice.
I use `set SCONS_MSCOMMON_DEBUG=ms_trace.log` in cmd shell and get the file.
[ms_trace.log](https://github.com/SCons/scons/files/9093803/ms_trace.log)
The log show I should install some software?

**Comment by 18611429192** [comment]
> Just for information, SCons won't, by default, use your environment variables like PATH. For Visual Studio / Build Tools from 2017 on, it uses the `vswhere.exe` command to work out where the compiler lives. The debug dump should show (along with many other things) the process of trying to do this, and _hopefully_ give clues as to why it's not finding it.

thank you for the advice, I push the log file to this issue.

**Comment by mwichmann** [comment]
What happens if you run vswhere by itself, like this:
```cmd
vswhere -property installationPath
```

**Comment by 18611429192** [comment]
> 
Magically, the output is actually empty. So I reinstalled Visual Studio and it works fine now. Thank you for your help.
