### ISSUE TITLE
SCons 4.4.0 ignores "absolute_import" imports in tools

### ISSUE THREAD

**Issue by ivankravets** [SConsProject/scons#4204]
Hi there,

We have [a bunch of custom tools](https://github.com/platformio/platformio-core/tree/develop/platformio/builder/tools) in PlatformIO. Some of them depend on the 3rd party modules already installed by PlatformIO Core). The `from __future__ import absolute_import` helped us import them. 

Nevertheless, the latest SCons 4.4.0 fails with "ImportError".

For example, in this line  https://github.com/platformio/platformio-core/blob/develop/platformio/builder/tools/platformio.py#L29

-----

Yes, we can refactor all our tools and patch "sys.path" in the run-time. However, the other users of SCons also could be affected by this new release who use absolute imports for tools.

**Comment by mwichmann** [comment]
This is odd... `absolute_import` has always been the Python 3 behavior, so the import from future should be meaningless.  Is there a better way to zero in on what is going wrong?

**Comment by bdbaddog** [comment]
It's not clear what the issue is here.
A stack trace or minimal reproducer's needed.

**Comment by mwichmann** [comment]
I'm presuming I broke something trying to update the tool importing not to use deprecated importlib (or, worse, imp) methods, so there's something we're not testing for, I guess.  I don't see how the example cited in the link could possibly be affected by that as it's not an SCons tool import, so clearly I'm missing something

**Comment by ivankravets** [comment]
Thanks for the quick response! Here is the log:

```
ImportError: cannot import name '__version__' from 'platformio' (platformio/builder/tools/platformio.py):
  File "platformio/builder/main.py", line 102:
    env = DefaultEnvironment(**DEFAULT_ENV_OPTIONS)
  File "~/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Defaults.py", line 83:
    _default_env = SCons.Environment.Environment(*args, **kw)
  File "~/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Environment.py", line 1030:
    apply_tools(self, tools, toolpath)
  File "~/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Environment.py", line 116:
    _ = env.Tool(tool)
  File "~/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Environment.py", line 1905:
    tool = SCons.Tool.Tool(tool, toolpath, **kwargs)
  File "~/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Tool/__init__.py", line 118:
    module = self._tool_module()
  File "~/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Tool/__init__.py", line 201:
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 850:

  File "<frozen importlib._bootstrap>", line 228:

  File "platformio/builder/tools/platformio.py", line 28:
    from platformio import __version__, fs
```

**Comment by bdbaddog** [comment]
Can you make a small reproducer? (smaller than installing platformio would be ideal.. )

**Comment by ivankravets** [comment]
It's very easy to reproduce. Try to create Python virtual environment and install any Python package. For example, `requests`. Now, try to `import requests` from the custom `tool` when calling `python path/to/local/scons.py` from this virtual environment.

**Comment by ivankravets** [comment]
> Can you make a small reproducer? (smaller than installing platformio would be ideal.. )

Yes, if the hint above is not enough to reproduce, I'll create a simple project.

**Comment by mwichmann** [comment]
Okay, that is indeed a change made recently, since `load_module` was declared obsolete...
```py
  File "/Users/ikravets/.platformio/packages/tool-scons/scons-local-4.4.0/SCons/Tool/__init__.py", line 201:
    spec.loader.exec_module(module)
```
Seems our tests must be insufficient to catch whatever damage this caused.

**Comment by ivankravets** [comment]
@mwichmann, is this our mistake on how do we import external Python modules using `from __future__ import absolute_import`? As I mentioned above, we can refactor our codebase. I filed the issue just to track if other users will face the same problem.

**Comment by mwichmann** [comment]
I don't see you doing anything wrong; the import from future should be a no-op as I understand it - it means nothing anymore, but Python promises never to remove anything from `__future__`.  Will take a look presently.

The motivator was python/cpython#70319, which is quite old, but recently gained more impetus as removal is scheduled for 3.12 (I think)

**Comment by bdbaddog** [comment]
@ivankravets - what's the lowest version of python PlatformIO supports?

**Comment by ivankravets** [comment]
@bdbaddog the same as SCons, v3.6.

**Comment by bdbaddog** [comment]
> It's very easy to reproduce. Try to create Python virtual environment and install any Python package. For example, `requests`. Now, try to `import requests` from the custom `tool` when calling `python path/to/local/scons.py` from this virtual environment.

ninja tool should also break then?

**Comment by ivankravets** [comment]
Please sorry for the false issue and that I stole your time 😢  This is our issue. We had a tool named "platformio" which led to the module name clashing. I've just renamed it to `piobuild` and 4.4.0 works great! ( see https://github.com/platformio/platformio-core/commit/5e8eb7709044862e93b3937c2e86b3111ffb3f71 )

Thanks again for your invaluable work! 🙏

**Comment by mwichmann** [comment]
whew!

**Comment by ivankravets** [comment]
Yes, sorry. We also removed all "absolute_import" and it works well.

Please note that the previous version of PlatformIO Core works well with SCons 4.3. It seems the issue is related to the recent changes with "import modules".

Nevertheless, glad that we can use the latest SCons version. We already bumped 4.4.0 to the [PlatformIO Registry](https://registry.platformio.org/tools/platformio/tool-scons). This is a copy of "scons-local" with removed "docbook" to save disk space and speed up downloading.

**Comment by mwichmann** [comment]
Yeah, the search changed a little bit, and I think that may have led to it being more inclined to pick something already imported if there's a name clash. I'll try to make myself a reminder to check that this didn't end up with a logical problem.
