### ISSUE TITLE
Unable to Install Multiple Versions of SCons Side-by-Side for SCONS 4.2.0

### ISSUE THREAD

**Issue by BGrandhi** [SConsProject/scons#4257]
Hi,
For my development works, I need to have multiple versions of scons installed on my PC (SCONS-3.1.2 and SCONS-4.2.0). I went through the SCONS user guide for finding some info for a way to achieve this and find out I can use an command **python setup.py install --version-lib** 
The above command worked fine when I am trying to install SCONS 3.1.2 but when I try to install SCONS 4.2.0 then it fails saying **error: option --version-lib not recognized** . 
Can you please help me with a way to achieve this so that I can work with two versions of scons on my PC? 
Thanks and please let me know if you need any more info.

**Comment by BGrandhi** [comment]
Here is the cmd output I am receiving  when I try to install SCONS 4.2.0

C:\Users\grb1rlz\Desktop\AllStuff\EXE\AllOrganized\BuildTools\scons\scons-4.2.0>python setup.py install --version-lib
C:\Users\GRB1RLZ\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'project-urls' will not be supported in future versions. Please use the underscore name 'project_urls' instead
  warnings.warn(
C:\Users\GRB1RLZ\AppData\Local\Programs\Python\Python39\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'dist-dir' will not be supported in future versions. Please use the underscore name 'dist_dir' instead
  warnings.warn(
usage: setup.py [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
   or: setup.py --help [cmd1 cmd2 ...]
   or: setup.py --help-commands
   or: setup.py cmd --help

error: option --version-lib not recognized

**Comment by bdbaddog** [comment]
This is not a bug. The proper channel to ask is via the users mailing list, the IRC channel or the discord server.
https://scons.org/contact.html

You should use python virtualenvs.
https://github.com/SCons/scons/blob/master/README.rst#installation
