### ISSUE TITLE
Remove from Users Guide: 1.3.1. Building and Installing Multiple Versions of SCons Side-by-Side

### ISSUE THREAD

**Issue by bdbaddog** [SConsProject/scons#4259]
The section advises using --version-lib arg to setup.py which is long dead.
Perhaps change to recommend/instruct to use virtualenv?

**Comment by mwichmann** [comment]
Yeah.  I tried to sketch an outline of that in #4258 maybe some variant of that could be used.

**Comment by mwichmann** [comment]
Before I dive in on this, how about some commentary on each of the sections of chapter 1 - what should we keep/change, etc.
