### ISSUE TITLE
VariantDir does wrong placement of Fortran *.mod files and doesn't clean the copies

### ISSUE THREAD

**Issue by band-a-prend** [SConsProject/scons#4286]
**Describe the bug**
Then use `VariantDir` function ([SCons:VariantDir](https://scons.org/doc/production/HTML/scons-user/ch15s04.html)) the unexpected behaviour of placement of Fortran `*.mod` files is observed. 

1. Without setup `duplicate` argument the `*.mod` files are presented also where source files are placed.
2. The running of `scons -c` doesn't clean destination directory and create symlink to `*.mod` - initially it wasn't symlink.

3. If  `duplicate=False`  is used then *.mod files are created where are source files instead of destination directory.

**Required information**
* Link to SCons Users thread discussing your issue. none
* Version of SCons 4.4.0
* Version of Python 3.10.9
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc): system package (Gentoo Linux)
* How you installed SCons: via system package manager (Gentoo Linux)
* What Platform are you on? (Linux/Windows and which version): Gentoo Linux x86_64
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.

1. To reproduce I used simple Fortran program example from [Fortan-lang.org Learn section](https://fortran-lang.org/en/learn/building_programs/linking_pieces/):

`tabulate.f90`:
```
program tabulate
    use user_functions

    implicit none
    real    :: x, xbegin, xend
    integer :: i, steps

    write(*,*) 'Please enter the range (begin, end) and the number of steps:'
    read(*,*)  xbegin, xend, steps

    do i = 0, steps
        x = xbegin + i * (xend - xbegin) / steps
        write(*,'(2f10.4)') x, f(x)
    end do
end program tabulate
```
and `functions.f90`:
```
module user_functions
    implicit none
contains

real function f( x )
    real, intent(in) :: x
    f = x - x**2 + sin(x)
end function f

end module user_functions
```
with the following `SConstruct` file (similar to that is presented in [SCons User Guide](https://scons.org/doc/production/HTML/scons-user/ch15s04.html)):
```
VariantDir('build', '.')
env = Environment()
env.Program('build/my_proj', ['build/tabulate.f90', 'build/functions.f90'])
```
i.e. the `my_proj` executable is placed to `./build` directory too.
2. Run `scons` command and see the result directory structure - **`user_functions.mod` is also placed in source files directory**:
```
.
├── SConstruct
├── build
│   ├── functions.f90
│   ├── functions.o
│   ├── my_proj
│   ├── tabulate.f90
│   ├── tabulate.o
│   └── user_functions.mod
├── functions.f90
├── tabulate.f90
└── user_functions.mod
```
3. Run `scons -c` and notice that 
```
.
├── SConstruct
├── build
│   ├── functions.f90
│   ├── tabulate.f90
│   └── user_functions.mod -> /home/user/projects/scons_proj/user_functions.mod
├── functions.f90
└── tabulate.f90

```
where `build/user_functions.mod` is dead link and `build/*.f90` are still presented while **expected to be removed on clean**.

4. Now change `SConstruct` with addition of `duplicate=False` argument:
```
VariantDir('build', '.', duplicate=False)
env = Environment()
env.Program('build/my_proj', ['build/tabulate.f90', 'build/functions.f90'])
```
5. Remove all previous build artifacts (`build` directory):
6. Run `scons` command again and see the result directory structure, **notice that `user_functions.mod` is in source files (root) directory intead of `./build` directory**:
```
.
├── SConstruct
├── build
│   ├── functions.o
│   ├── my_proj
│   └── tabulate.o
├── functions.f90
├── tabulate.f90
└── user_functions.mod
```
7. Run `scons -c` and notice that this time all duplicates are removed properly: `build` directory is empty and there are no any source files.

* How you invoke scons (The command line you're using "scons --flags some_arguments"):
`scons` and `scons -c` are running only.

**Comment by band-a-prend** [comment]
Issue is reproduced in Linux Mint 21.1 Vera (base on Ubuntu 22.04 LTS Jammy): scons 4.0.1, python 3.10.6

**Comment by mwichmann** [comment]
Note: we don't recommend mapping `'.'` as the source directory.

Placement of module files is controlled by `FORTRANMODDIR`.  This doesn't make a lot of sense to me when dealing with a variant directory (why wouldn't it be placed in the variant dir?), but it is documented:

https://scons.org/doc/production/HTML/scons-man.html#cv-FORTRANMODDIR

**Comment by band-a-prend** [comment]
I expect the result will be the same if source files will be placed into `src` directory as I initially experimented with it. 

Great thanks for reference to FORTRANMODDIR - I also thinking about splitting the obj and mod files later. It make certain sence placing.mod files separately since it possible to install entire directory with modules files without filtering.

I will recheck the results with  mentioned variable for modules and will make feedback.

**Comment by mwichmann** [comment]
yes, the `.mod` files will still go into the top directory if you move the sources into a subdir.

**Comment by band-a-prend** [comment]
@mwichmann 
Thank you for clarification. The fortran flags of scons slightly confusing sometimes due to multiple standards - it's a good thing and a headache at the same time.

Well, but why on step 3 the dead symlink is created? If `scons -c` is called second time then it will be deleted. Initially it wasn't symlink before cleaning up.

I'm not sure if sorce files should be still presented in `build` dir after `scons -c` at this step 3 too.

**Comment by mwichmann** [comment]
That's some aspect of variantdir behavior. Will have to check into it. I think there's some other issue floating around about indirect targets (ones you didn't specifically call a builder for) not being cleaned so maybe that's related.

**Comment by band-a-prend** [comment]
It turned out that files within `build` directory are linked to original files (not symlinks) and are not just the copies. Then it explains that if `duplicate=False` isn't set then if original `*.mod` is removed by cleaning up while all links to (and `*.f90` too) are left. If this is that logic (such behavior is faster instead of real copying) than my issue is invalid.

**Comment by band-a-prend** [comment]
@mwichmann 
as you mentioned above it isn't recommended to use `.` as map to source drectory. I tried to use `src` for `*.f90` and then with `SConstruct` file:
```python
VariantDir('build/obj', 'src')
env = Environment(FORTRANMODDIR='build/include')
env.Program('build/my_proj', ['build/obj/tabulate.f90', 'build/obj/functions.f90'])
```

After `scons` call:
```
scons: Reading SConscript files ...
scons: done reading SConscript files.
scons: Building targets ...
gfortran -o build/obj/functions.o -c -Jbuild/include build/obj/functions.f90
gfortran -o build/obj/tabulate.o -c -Jbuild/include build/obj/tabulate.f90
gfortran -o build/my_proj build/obj/tabulate.o build/obj/functions.o
scons: done building targets.
```
I got directory structure:
```
.
├── SConstruct
├── build
│   ├── include
│   │   └── user_functions.mod
│   ├── my_proj
│   └── obj
│       ├── functions.f90
│       ├── functions.o
│       ├── tabulate.f90
│       └── tabulate.o
└── src
    ├── functions.f90
    └── tabulate.f90
```
and structure after `scons -c` call:
```
.
├── SConstruct
├── build
│   ├── include
│   └── obj
│       ├── functions.f90
│       └── tabulate.f90
└── src
    ├── functions.f90
    └── tabulate.f90
```
And as `obj/*.f90` are linked to `src/*.f90` that **it seems ok**.

If the following `SConstruct` file is used:
```python
VariantDir('build/obj', 'src', duplicate=False)
env = Environment(FORTRANMODDIR='build/include')
env.Program('build/my_proj', ['build/obj/tabulate.f90', 'build/obj/functions.f90'])
```
after `scons` call the following directory structure is got (the `scons` output is the same as above):
```
.
├── SConstruct
├── build
│   ├── include
│   │   └── user_functions.mod
│   ├── my_proj
│   └── obj
│       ├── functions.o
│       └── tabulate.o
└── src
    ├── functions.f90
    └── tabulate.f90
```
and after `scons -c`:
```
.
├── SConstruct
├── build
│   ├── include
│   └── obj
└── src
    ├── functions.f90
    └── tabulate.f90
```
where `build/obj` and `build/include` directories are empty as expected. So it works **OK too**.

So if `.` isn't used in `VariantDir` then all works as expected if `FORTRANMODDIR` is set up for `Environment`.
Therefore for Fortran as *specific case* the using of `VariantDir` the flag `FORTRANMODDIR` should be explicitly specified (maybe with some additional restriction).

Great thanks with and with help about additional Fortran setup.

Could I then close the issue?

**Comment by bdbaddog** [comment]
Yes. And next time please follow the request to bring your issue to our users mailing list, IRC channel, or (most likely to get quicker response) discord server.

**Comment by bdbaddog** [comment]
Closing
