### ISSUE TITLE
the output TEMPFILE on Windows does not have correct path for GCC

### ISSUE THREAD

**Issue by zxtxin** [SConsProject/scons#4298]
**Describe the bug**
TempFileMunge generates RSP files on Windows with paths in the following format:

path\to\file1.obj
path\to\file2.obj
...

At linkage state linker is called with path separator missing:

pathtofile1.obj

This is the same problem as nijia https://github.com/ninja-build/ninja/pull/1627

** Background **

I'm using arm-gcc on windows with the following toolchain file
```
from SCons.Tool import cc,cxx,ar,link
import importlib
assembler = importlib.import_module('SCons.Tool.as')

def generate(env):

    cc.generate(env)
    cxx.generate(env)
    assembler.generate(env)
    ar.generate(env)
    link.generate(env)
    env['CC'] = 'arm-none-eabi-gcc'
    env['CXX'] = 'arm-none-eabi-g++'
    env['AS'] = 'arm-none-eabi-gcc'
    env['AR'] = 'arm-none-eabi-gcc-ar'
    env['OBJDUMP'] = 'arm-none-eabi-objdump'
    env['OBJCOPY'] = 'arm-none-eabi-objcopy'
    env['NM'] = 'arm-none-eabi-nm'
    env['READELF'] = 'arm-none-eabi-readelf'
    env['PROGSUFFIX'] = '.elf'    
    
def exists(env):
    return True
```

**Comment by dmoody256** [comment]
you can customize the tempfile output with this function when using posix compilers on windows:
```
from SCons.Subst import quote_spaces
def tempfile_arg_esc_func(arg):
    arg = quote_spaces(arg)
    return arg.replace('\\', '/')
env["TEMPFILEARGESCFUNC"] = tempfile_arg_esc_func
```

This might help with your issues

**Comment by bdbaddog** [comment]
> you can customize the tempfile output with this function when using posix compilers on windows:
> 
> ```
> from SCons.Subst import quote_spaces
> def tempfile_arg_esc_func(arg):
>     arg = quote_spaces(arg)
>     return arg.replace('\\', '/')
> env["TEMPFILEARGESCFUNC"] = tempfile_arg_esc_func
> ```
> 
> This might help with your issues

Note: This is direct from the manpage.

**Comment by bdbaddog** [comment]
Also please paste code, not screen shots. (Screen shots can't be copy/pasted/and edited)
And it seems you ignored our request to bring your issues to the mailing list, IRC, or discord server before filing an issue.

**Comment by bdbaddog** [comment]
You did not need to use the importlib logic.
You can simply call `env.Tool('as')`, same with gcc,etc..

**Comment by zxtxin** [comment]
I'm a newbie. I'm sorry for breaking the rule. I've turned the screen shot into code.
Thank you very much for providing the solution.

**Comment by bdbaddog** [comment]
> I'm a newbie. I'm sorry for breaking the rule. I've turned the screen shot into code. Thank you very much for providing the solution.

@zxtxin  - No worries. We all start somewhere.  Jumping on the discord server is probably going to be the fastest way to get help with any issue in general.
