### ISSUE TITLE
On windows user can't write unicode symbols to file

### ISSUE THREAD

**Issue by RedwanFox** [SConsProject/scons#4302]
SCons: v4.4.0.fc8d0ec215ee6cba8bc158ad40c099be0b598297 (installed via scoop)
Python 3.11.0 (default distribution)
Windows 11

Bug description: On windows user can't write unicode symbols to file, because default encoding is cp1251

This can be easily fixed by adding utf-8 encoding here
https://github.com/SCons/scons/blob/440728dd1d9fee6a8e010b4d9871737686cb3afb/SCons/Tool/textfile.py#L122

```
Traceback (most recent call last):
  File "C:\Users\Redwan\scoop\apps\scons\4.4.0\scons-local-4.4.0\SCons\Action.py", line 1318, in execute
    result = self.execfunction(target=target, source=rsources, env=env)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Redwan\scoop\apps\scons\4.4.0\scons-local-4.4.0\SCons\Tool\textfile.py", line 132, in _action
    target_file.write(_do_subst(line, subs))
  File "C:\Program Files\Python311\Lib\encodings\cp1251.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode character '\xd7' in position 8177: character maps to <undefined>
scons: building terminated because of errors.
[Time elapsed: 00:00:02.645]
```

Way to reproduce:
Try to write unicode symboles using `env.Textfile` on windows .

**Comment by mwichmann** [comment]
pylint now warns about open without specifying encoding, but due to the volume of grumbles (some of them not ever going to get fixed - SCons has its particular function/class naming style and it's not going change wholesale) - this is not yet general, but only being done on files that otherwise get heavily worked on.  So I pretty much agree with the proposal...

**Comment by mwichmann** [comment]
@bdbaddog this is failing `test\textfile\textfile.py` on Windows - all four of the appveyor builds failed on new PR #4305, and I can reproduce here, so something still isn't quite right. Reopening here, so it's recorded (seems silly to add a new issue).
```txt
1255/1271 (98.74%) C:\Python311\python.exe test\textfile\textfile.py
Unexpected contents of `foo1.txt'
contents =======================================================================
6c6
< �
---
> ×
FAILED test of C:\projects\scons\scripts\scons.py
	at line 522 of C:\projects\scons\testing\framework\TestCommon.py (must_match)
	from line 78 of C:\projects\scons\test\textfile\textfile.py
Test execution time: 1.2 seconds
```

**Comment by bdbaddog** [comment]
> @bdbaddog this is failing `test\textfile\textfile.py` on Windows - all four of the appveyor builds failed on new PR #4305, and I can reproduce here, so something still isn't quite right. Reopening here, so it's recorded (seems silly to add a new issue).
> 
> ```
> 1255/1271 (98.74%) C:\Python311\python.exe test\textfile\textfile.py
> Unexpected contents of `foo1.txt'
> contents =======================================================================
> 6c6
> < �
> ---
> > ×
> FAILED test of C:\projects\scons\scripts\scons.py
> 	at line 522 of C:\projects\scons\testing\framework\TestCommon.py (must_match)
> 	from line 78 of C:\projects\scons\test\textfile\textfile.py
> Test execution time: 1.2 seconds
> ```

I'll take a look a bit later..
