### ISSUE TITLE
Add support for the GNU Bison option `-H`

### ISSUE THREAD

**Issue by piotrsiupa** [SConsProject/scons#4327]
SCons doesn't recognize the option `-H`.
It should update the list of output files when the option is encountered. The option `-H` is the same as `--header` or `--defines` which are currently supported. (Well, kinda. See: https://github.com/SCons/scons/issues/4326)
(https://www.gnu.org/software/bison/manual/bison.html#Output-Files)

* Link to SCons Users thread discussing your issue. - https://discord.com/channels/571796279483564041/571796280146133047/1087434623476301836
* Version of SCons - v4.5.1.49578b34582d9e92dac7d713a8e58599ae35aa63
* Version of Python - 3.10.6
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc) - the one from Ubuntu repository
* How you installed SCons - through `pip`
* What Platform are you on? (Linux/Windows and which version) - Linux Mint
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues. - it's below
* How you invoke scons (The command line you're using "scons --flags some_arguments") - `scons`

```
targets = CFile('foo.y', YACCFLAGS='-d')
print('Flag `-d` (correct target list):', targets)

targets = CFile('bar.y', YACCFLAGS='-H')
print('Flag `-H` (incorrect target list):', targets)
```

**Comment by mwichmann** [comment]
Seems "obvious", but it's a little harder to parse: `--header` (and its now-obsolete synonym `--defines`) use an `=` to indicate there's a following option-argument (filename).  `-H` does not, you have to just concatenate the filename directly with the option (same for `-g`).
