### ISSUE TITLE
Remove bootstrap.py from tree (Long obsoleted)

### ISSUE THREAD

**Issue by bdbaddog** [SConsProject/scons#4341]
This script has been obsoleted since 2020.
And it has been issuing the following message when run since then.
```
   print("Please use")
    print("python scripts/scons.py")
    print("Instead of python bootstrap.py. Bootstrap.py is obsolete")
```

**Comment by mwichmann** [comment]
Sure this won't cause compatibility problems?  :)

**Comment by mwichmann** [comment]
`doc/SConscript` does import and use bootstrap.
```py
src_files = bootstrap.parseManifestLines('.', manifest)
```

**Comment by bdbaddog** [comment]
> `doc/SConscript` does import and use bootstrap.
> 
> ```python
> src_files = bootstrap.parseManifestLines('.', manifest)
> ```

Beautiful..

But looks like it only needs the `parseManifestLines` ?

**Comment by mwichmann** [comment]
couldn't find anything else, no

**Comment by mwichmann** [comment]
maybe move the manifest parser to something in site_scons?

**Comment by bdbaddog** [comment]
If that's the only use, maybe just migrate into doc/SConstruct.. I'll have to take a look to see how big both the function in question and the doc/SConstruct are to see if that'd be too ugly. otherwise `doc/site_scons/site_init.py` would be a good place for that function.

**Comment by mwichmann** [comment]
it's pretty small, but a lot of utility functions for scons "build" are in the site_scons tree, so either way.
