### ISSUE TITLE
Configure.CheckLib() error with -Wstrict-prototypes

### ISSUE THREAD

**Issue by JonathonReinhart** [SConsProject/scons#4373]
This is a continuation of #3095. As noted in [this comment](https://github.com/SCons/scons/pull/3096/files#r1257532304), there was one more instance that was missed in PR #3096:

https://github.com/SCons/scons/blob/810ca6c8895b01cbd636d83079f6a848dc36adf6/SCons/Conftest.py#L677-L684

**Comment by mwichmann** [comment]
Thanks for spotting, you're quite right.  I'll take this; might also normalize the formatting a little on some of the other C snippets.  Line breaking seems to be... well, breaking... various things these days: e.g. Python code formatters may break a function signature into multiline, and then it doesn't look right in tracebacks, debugger, etc.

**Comment by JonathonReinhart** [comment]
FYI I already submitted PR #4374. I mentioned it in the commit but not the PR, so it wasn't linked.

**Comment by mwichmann** [comment]
ah, ok.
