### ISSUE TITLE
run document test failed

### ISSUE THREAD

**Issue by LiuYinCarl** [SConsProject/scons#4415]
I try to send a emal to scons-users@scons.org first, but failed, so I make a issue.
> host mailwash62.pair.com[66.39.2.62] said: 554 5.7.1 Service unavailable; Client host [203.205.251.36] blocked using sip24.invaluement.local (in reply to RCPT TO command)

I am using scons and want to test the edition of the scons' user guide, such as 'scons/doc/user/simple.xml'. Here's what I do,

```bash
$ cd scons/

$ python3 --version
Python 3.10.12

$ python3 bin/docs-update-generated.py
Generating entity files...
Validating files against SCons XSD...
0.88% (1/113) SCons/Action.xml
Traceback (most recent call last):
  File "/home/lzh/github/scons/bin/scons-proc.py", line 409, in <module>
    if SConsDoc.validate_all_xml(['SCons']):
  File "/home/lzh/github/scons/bin/SConsDoc.py", line 464, in validate_all_xml
    if not tf.validateXml(fp, xmlschema_context):
  File "/home/lzh/github/scons/bin/SConsDoc.py", line 359, in validateXml
    TreeFactory.xmlschema = etree.XMLSchema(xmlschema_context)
AttributeError: module 'xml.etree.ElementTree' has no attribute 'XMLSchema'
Generation failed
```

then I read the source code of `scons/bin/SConsDoc.py` and found such code

```python
 138 try:
 139     from lxml import etree
 140 except ImportError:
 141     try:
 142         import xml.etree.ElementTree as etree
 143     except ImportError:
 144         raise ImportError("Failed to import ElementTree from any known place")
```

So I try to import the two module in Python interpreter and find the "lxml" module is not a
Python build-in module and it has no "xml.etree.ElementTree.XMLSchema()" function.

```bash
$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'lxml'
>>> import xml
>>> import xml.etree.ElementTree as etree
>>> hasattr(etree, "XMLSchema")
False
```

Then I try to install "lxml" by pip and try again.

```bash
$ python3 -m pip install lxml
# ......
Successfully installed lxml-4.9.3

$ python3
Python 3.10.12 (main, Jun 11 2023, 05:26:28) [GCC 11.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lxml
>>> from lxml import etree
KeyboardInterrupt
>>> hasattr(etree, "XMLSchema")
True
```
Finally, run test again and success.

```bash
$ python3 bin/docs-update-generated.py
Generating entity files...
Validating files against SCons XSD...
0.88% (1/113) SCons/Action.xml
1.77% (2/113) SCons/Defaults.xml
# ......
99.12% (112/113) SCons/Tool/yacc.xml
100.00% (113/113) SCons/Tool/zip.xml
OK
Updating documentation for builders, tools and functions...
Done
```

So, I think if scons can only with "lxml" module, maybe remove the code below is better.

```python
 138 try:
 139     from lxml import etree
 140 except ImportError:
 141     try:
 142         import xml.etree.ElementTree as etree
 143     except ImportError:
 144         raise ImportError("Failed to import ElementTree from any known place")
```

**Comment by mwichmann** [comment]
To set up to "do everything" (be able to construct the SCons package and/or docs), use the `requirements-pkg.txt`; to "develop" SCons use the lighter-weight `requirements-dev.txt` (the former includes the latter). The base `requirements.txt` is for using SCons, but not for hacking on SCons; it has no actual dependencies listed (this is actually documented someplace, but we don't expect SCons learners to need to build the doc set, so it's not in the user guide).

And yes, there was a transitional period when either the stdlib `xml` or the external `lxml` could be used, but the xml-only approach stopped working. A cleanup is in order, but there are lots of things that need attention.

**Comment by bdbaddog** [comment]
re email. The host is moving from one machine to another, so this may be a glitch caused by that.

**Comment by bdbaddog** [comment]
To do the doc build you'll also need to install a handful of system packages.
There's a script to do so, but it may be out of date.
try running `bin/scons_dev_master.py building`
