### ISSUE TITLE
4.6.0 distfile: contains pycache files for Python 3.11

### ISSUE THREAD

**Issue by 0-wiz-0** [SConsProject/scons#4455]
It seems there was a bug in creating the 4.6.0  pypi distfile, it contains a pycache file for Python 3.11:
```
drwxr-xr-x  0 bdbaddog staff       0 Nov. 20 02:22 SCons-4.6.0/SCons/Tool/docbook/__pycache__/
-rw-r--r--  0 bdbaddog staff   37254 Juli 15 02:13 SCons-4.6.0/SCons/Tool/docbook/__pycache__/__init__.cpython-311.pyc
```
Please make sure this doesn't happen again. Thanks!

**Comment by mwichmann** [comment]
Hmmm, thought there was logic to avoid that. I'm only seeing a filter for scons-local though. @bdbaddog ?

**Comment by bdbaddog** [comment]
@0-wiz-0 - Clearly this was not intentional, we'll do our best.

**Comment by bdbaddog** [comment]
I'm not even sure how that happened at all to be clear. We'll have to figure it out. We're using the normal wheel building logic..

**Comment by bdbaddog** [comment]
Hmm. Did a `git clean -xfd` and then rebuilt and no .pyc. I'll upload a 4.6.0.post1 package shortly.

**Comment by bdbaddog** [comment]
4.6.0.post1 has been uploaded to pypi.
@0-wiz-0  - please download and let us know if this fixes the issue you've reported.
Thanks!

**Comment by 0-wiz-0** [comment]
Thank you, the new release tarball is fine!

**Comment by bdbaddog** [comment]
@0-wiz-0 - great. We've updated our release procedure to do git clean -xfd going forward, so hopefully that prevents a repeat.
