### ISSUE TITLE
Typo in user documentation

### ISSUE THREAD

**Issue by Prabhu-LANL** [SConsProject/scons#4458]
There is a typo in: https://github.com/SCons/scons/blob/master/doc/user/preface.xml
It says "construction too" instead of "construction tool" - i.e. the 'l' is missing from the word "tool"

**Comment by Prabhu-LANL** [comment]
I wanted to open a pull request to just fix it myself, but I don't seem to be able to create a bugfix/feature branch. I'm at work where discord is blocked, so that's why I just went ahead and opened the issue. Thanks.

**Comment by bdbaddog** [comment]
see this wiki page. You should be able to fork the project and create  branch in your fork..
https://github.com/SCons/scons/wiki/DevGuide-GitWorkflows

**Comment by Prabhu-LANL** [comment]
Thanks, I was actually just working on that :-)

**Comment by Prabhu-LANL** [comment]
https://github.com/SCons/scons/pull/4459

**Comment by Prabhu-LANL** [comment]
> see this wiki page. You should be able to fork the project and create branch in your fork.. https://github.com/SCons/scons/wiki/DevGuide-GitWorkflows

This link appears blank for me?
![scons_screenshot](https://github.com/SCons/scons/assets/109241084/a17aa498-f24a-4782-b6e3-3db18a6bf84f)

**Comment by mwichmann** [comment]
It was renamed in error, just renamed back. Try:

https://github.com/SCons/scons/wiki/GitWorkflows

**Comment by Prabhu-LANL** [comment]
> It was renamed in error, just renamed back. Try:
> 
> https://github.com/SCons/scons/wiki/GitWorkflows

Now I wish I could remember where I first found that link, so I could fix the link in a separate PR. Or maybe I found it in the wiki? Probably since you're actively working on it you'll be updating the incoming links to that page?
Thanks!

**Comment by Prabhu-LANL** [comment]
@mwichmann We're almost neighbors - hehe. Last time I drove through Questa was this past summer - on my way with my wife and 3 boys to finally see the Rio Grande Del Norte National Monument. It was pretty awesome!

**Comment by mwichmann** [comment]
yes (to the wiki question)

**Comment by mwichmann** [comment]
> @mwichmann We're almost neighbors - hehe. Last time I drove through Questa was this past summer - on my way with my wife and 3 boys to finally see the Rio Grande Del Norte National Monument. It was pretty awesome!

yup, the view out the western windows looks over the valley, to San Antonio Mtn, with the monument area and the canyon in between.  Not actually in Questa, which has hills in the way, but north of there.  That's quite a "hole in the ground" :-)
