### ISSUE TITLE
Support Tracking Custom Beamer Themes in LaTeX

### ISSUE THREAD

**Issue by kprussing** [SConsProject/scons#4620]
**Describe the Feature**

The beamer package provides a mechanism for customizing presentations via 'themes'. Beamer defines five types of theme: a general theme, a color theme, a font theme, an inner theme, and an outer theme. These are enabled with the commands:

```latex
\usetheme{mwe}
\usecolortheme{mwe}
\usefonttheme{mwe}
\useinnertheme{mwe}
\useoutertheme{mwe}
```

The themes function like packages loaded via `\usepackage` except the file names are converted to `beamer(|color|font|inner|outer)mwe.sty`. If a user has a custom version in their project, SCons should pick these files (and their further includes) as dependencies of a document.

**Required information**
* Link to SCons Users thread discussing your [issue](https://discord.com/channels/571796279483564041/1296961428762394699).
* Version of SCons: 4.8.0
* Version of Python: 3.12.4
* Which python distribution if applicable (python.org, cygwin, anaconda, macports, brew,etc): anaconda
* How you installed SCons: scons-local (and `pip install scons`)
* What Platform are you on? (Linux/Windows and which version): macOS
* How to reproduce your issue?  Please include a small self contained reproducer. Likely a SConstruct should do for most issues.: A minimal working example with explanation of desired outputs is [here](https://github.com/kprussing/scons-beamer-support-mwe)
* How you invoke scons (The command line you're using "scons --flags some_arguments"): `scons`

**Additional context**

I have a custom theme for work that I would like SCons to track for changes.

**Comment by mwichmann** [comment]
Should have been closed by merging #4621
