### ISSUE TITLE
`env.Dictionary` does not return a dictionary when any arguments are specified.

### ISSUE THREAD

**Issue by ghost** [SConsProject/scons#4631]
**Describe the bug**
Method with name `Dictionary` should always return type **dict**. If you pass no args, it will return dict of all construction variables. 

If you pass there args (names of construction variables you are interested in), you should get in return **dict** containing only the keys requested.

There is method `env.get(<name>)` or `env["<name>"]`. 

Currently if an argument(s) are passed it behaves more like a `get` function which allows to retrieve on or more values at a time.

Change requested:

* Method `get` which allows `str | dict[str]` and returns one or multiple values...
* Method `get_default` which works like current `get`
* Method `Dictionary` which works the same if no args and returns **DICTIONARY** if args were supplied

**Required information**
* Version of SCons 4.8.1
* Version of Python

**Comment by ghost** [comment]
And just additionally why I needed it. I needed to get dictionary with only variables which are part of specific `Variables`

```python
options = Variables()
options.Add(...)
....
....
print(env.Dictionary(list(options.keys())))
``` 

As in the end I obviously have two lists I can obviously construct dictionary by myself using `dict(zip(keys_list, values_list))` but anyway API is broken

**Comment by ghost** [comment]
I can even propose following for a bit better backward compatibility. If user passes one or two args which are both strings, `get` do as usually. If user passes there list or tuple of strings or something like it, it does the same as currently `Dictionary` with args does. It would be messy to implement but would allow to save a bit of backward compatibility.

I am going to try to implement it (I've read about your prefer to discuss for so I am ready the PR will be rejected... If I will ever manage to finish it)

**Comment by mwichmann** [comment]
there's an existing change (not pushed), which adds this behavior to Dictionary with a flag. I can make that available for a look.

**Comment by ghost** [comment]
> there's an existing change (not pushed), which adds this behavior to Dictionary with a flag. I can make that available for a look.

Ok. I'd like to see it. But "not pushed" and not among PR's :sweat_smile:

**Comment by mwichmann** [comment]
PR now.  It doesn't change the default behavior, partly because it likely wouldn't get approved that way, and partly because there are 150+ uses of the current behavior in the test suite, be a pain to modify (for some reason, usage like `tar = foo.Dictionary('TAR')` is very common).

**Comment by ghost** [comment]
Overall if trying to maintain backward compatibility as much as possible, adding new key is the best solution but it is hacky...

I saw that [4.0 deleted deprecated method](https://scons.org/scons-400-is-available.html) `Source Code`. It means there is a some deprecation pipeline in the project. From perspective of clearness, obviousness and soundness of API new key is a bad thing.... I understand backward compatibility so have another proposal. It is not the clearest though.

Currently `Dictionary` with arguments works as `get` but for multiple args and as you said it is even often used for one arg like `tar = foo.Dictionary('TAR')`. I tried (not thoroughly) to find methods with name `get` maybe there is ia option to add method `get_multiple` and warn user that current behavior of `Dictionary` is deprecated and they should use `get` or `get_multiple` instead when they call `Dictionary` as currently and stil add `as_dict` key which will be then over time converted to a default behavior?

**Comment by mwichmann** [comment]
The deprecation pipeline is slow and not as well-defined as it could be. In "the old days" it was written up as needing two major releases, but the release versioning now has settled into something a little like Python's - there have been a lot of 4.x releases without popping to 5.0, so the precise wording of that policy almost suggests we can't ever remove anything :-) . Yes, we could mark the current behavior as deprecated immediately and eventually flip the default. That's almost a separate question, but will wait for more general feedback.

**Comment by ghost** [comment]
It is sad... Because it means that not only "published" api won't change and that there will be much  slower process of turning "unpublsihed" to "published" api...

And there is no any <Idk how it is named>. Thing similar to [how wayland protocols works](https://gitlab.freedesktop.org/wayland/wayland-protocols#wayland-protocols) something like client requires to be present certain version of "protocol" (interconnected bunches of code) and uses it. Some times new version of "protocol" is released and clients which don't require new version of "protocol" just depend on old version of protocol. The wyland compositor itself ships support for some versions and one day old versions are dropped but they are isolated so there is no pain to drop it...

**Comment by bdbaddog** [comment]
@mwichmann  - no it does not.  Many things have been removed from SCons over time.

**Comment by bdbaddog** [comment]
Also there's no need to quote published or unpublished...

**Comment by mwichmann** [comment]
> @mwichmann - no it does not. Many things have been removed from SCons over time.

yes of course it's possible, just requires our discretion - all I was saying was the old policy as written doesn't quite fit.

**Comment by ghost** [comment]
> Also there's no need to quote published or unpublished...

It is for me personally because in this way it is easier to do substitution in mind. I internally use stable/unstable or public/private and quotes remind me a little bash syntax for expanding :P

**Comment by bdbaddog** [comment]
I've updated the description and title to be clearer and more professionally written.
