### ISSUE TITLE
Documentation is littered with typos

### ISSUE THREAD

**Issue by rico-chet** [SConsProject/scons#4635]
All the typo and grammar issues make a bad first impression on those considering using SCons.

This is a reminder to contribute from [the branch](https://github.com/rico-chet/scons/tree/fix-languagetool-complaints).

**Comment by mwichmann** [comment]
As written, this is not helpful. Details and/or patches will of course be considered.

**Comment by rico-chet** [comment]
It'll take a moment, I will split my work into commits ranging from obvious to disputable for more practicality.

**Comment by mwichmann** [comment]
Doing things in stages is fine - and perhaps preferable!

**Comment by rico-chet** [comment]
#4649 addresses more than 237 issues that I found with help of `languagetool`.

**Comment by mwichmann** [comment]
It's appreciated. Will be a lot for @bdbaddog to scroll through reviewing, but it looks straightforward enough.
