### ISSUE TITLE
`Clean()` parameter name mismatch between documentation and code

### ISSUE THREAD

**Issue by rico-chet** [SConsProject/scons#4638]
What documentation states:

> Clean(targets, files_or_dirs)

In fact, `files_or_dirs` cannot be used as a named argument, instead `files` works. Not sure which name is the intended one.

**Comment by mwichmann** [comment]
There are likely to be a lot of these, because of the long-ago choice to use separate documentation files rather than have the manpage snippets generated from the docstrings/code.

**Comment by bdbaddog** [comment]
Feel free to PR this.

Also.. you've deleted the request to bring your issues to the mailing list or discord server before filing them.
