### ISSUE TITLE
`UnknownVariables` doesn't return unknown variables defined in files

### ISSUE THREAD

**Issue by ghost** [SConsProject/scons#4645]
Running `scons` will print `{}`, while running `scons my_var="cli_value"` will print `{'my_var': 'cli_value'}`
```python
#custom.py
my_var="value"
```

```python
import SCons
from SCons.Variables import *

env = Environment()

options = Variables(["custom.py"], ARGUMENTS)
options.Add("my_option", "", "")

options.Update(env)

print(options.UnknownVariables())
```

**Comment by mwichmann** [comment]
The current manpage wording suggests "unknown" variables from files should indeed be flagged:

> Returns a dictionary containing any variables that were specified in the files and/or args parameters when `Variables` was called, but the object was not actually configured for.

**Comment by mwichmann** [comment]
I can confirm there's no processing of unknowns in the variables-file reading section. It just does an `exec` to add the assignments to the dict.
